### ISSUE TITLE
Issue running design.py on large files

### ISSUE THREAD

**Issue by EnriqueDoster** [broadinstitute/catch#32]
Hello catch developers, 

We've had a great experience using your software on a database of smaller genes, but now I am trying to make probes on > 60 genomes from a single bacterial species and the design.py script seems to get hung up. 

The fasta file is currently formatted such that each genome is a single header and sequence (mean = 2.7Mb) so I was wondering if this could be causing issues. I tried using flags that would improve performance, such as longer probe stride and the "--cluster-and-design-separately" flag, but I still could not get a result after letting it run for more than a week. It does not appear that memory is the issue because using htop shows that there was plenty of memory still available and nothing had jumped to swap. Do I just need to let the process keep running for as long as needed? What would you suggest I could do to run the probe design on the entire file at once?

For now, I'm splitting the probe design into groups of 5-10 genomes and this seems to be working fine, but I was wondering if I was missing a simple solution.

Thank you for your time,
Enrique

**Comment by haydenm** [comment]
Hi Enrique,

I’m glad that you had a great experience with CATCH on smaller genes, but am sorry to hear about the difficulties on the bacterial species. CATCH is indeed more tailored, out of the box, to large numbers of small genomes (e.g., viruses) rather than longer genomes. We have applied it to large numbers of bacterial whole genomes, so it is possible, just more involved.

Here are a few suggestions that you can try, in order from simple to more work:
1. In addition to `--cluster-and-design-separately`, you should set `--cluster-from-fragments`. A reasonable choice of values for you would be `--cluster-and-design-separately 0.1 --cluster-from-fragments 50000`. You could also add `--filter-with-lsh-hamming 2`, although this is not likely to do much with just ~60 genomes.
2. Split the genomes into smaller groups and running `design.py` on each group separately. It sounds like you already did this though, and it worked.
3. If you only care about sequencing genes, construct groupings of genes corresponding to different gene families and run `design.py` separately on each. You could then run `pool.py` across the gene families to accommodate differing levels of diversity.

We’ve done (3) before, but it is definitely the most involved. Let me know if (1) works. If it doesn’t, could you pass along the full list of command-line arguments you’re using? I can check if there’s something else there that might be slowing it down.

Hayden

**Comment by EnriqueDoster** [comment]
Hello Hayden,

Thanks for your response. Everything seems to have worked out fine after using your recommended values and adding a larger probe stride.

Best,
Enrique

**Comment by Ankita-1211** [comment]
Hi

I have 1500 bacterial genome, for which I want to make probe, so as to identify my microbiome environment sample. 

Please help me with parameters which can give me good specificity.
