### ISSUE TITLE
 identify conserved regions or regions suitable for differential identification, and design PCR primer

### ISSUE THREAD

**Issue by aiqubo** [broadinstitute/catch#39]
Hello catch developers,
"Moreover, CATCH can identify conserved regions or regions suitable for differential identification, which can help in the design of PCR primers and CRISPR–Cas13 crRNAs for nucleic acid diagnostics."
How can i use catch  identify conserved regions or regions suitable for differential identification, and design PCR primer ? Could you tell me the details ?

thanks 

qubo

**Comment by haydenm** [comment]
Hi qubo,

When we have used CATCH to help with designing PCR primers, we have usually done so with a relatively long probe length (e.g., `-pl` set to about 200 nt), and tolerating multiple mismatches, to identify conserved regions. We use the `--identify` argument to enforce specificity among the different input datasets (e.g., species). Then, we mine those output "probes"/regions to find suitable PCR primers, for example, using primer3.

Another more principled option is to use the `--custom-hybridization-fn` argument along with a probe length that matches your primer length. This argument lets you specify your own function that is dynamically loaded. (Run `http://design.py --help` for details.) You could define this function to return True if a probe/primer is suitable (similar to the target sequence and, e.g., matching desired secondary structure and melting temperature constraints) and False otherwise. An approach like this would directly output PCR primers, although you would still have to find satisfactory forward/reverse pairs. I have not personally used this for PCR primer design, but others have (see this [thread](https://twitter.com/gringene_bio/status/1244540732465016833)) for related applications.

Hayden

**Comment by aiqubo** [comment]
Thank you for your detailed answer, it gave me a lot of hints to think about.
